version: 2

builds:
  - id: terraform-provider-awsnomicon
    main: ./main.go
    binary: terraform-provider-awsnomicon
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: zip
    name_template: "terraform-provider-awsnomicon_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "terraform-provider-awsnomicon_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--armor"
      - "--detach-sign"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "-o"
      - "${signature}"
      - "${artifact}"

release:
  prerelease: auto
